/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#3525cd',
        'inverse-primary': '#c3c0ff',
        'primary-fixed-dim': '#c3c0ff',
        surface: '#f9f9ff',
        'on-primary-container': '#dad7ff',
        'surface-variant': '#dce2f7',
        'on-error-container': '#93000a',
        'on-secondary-fixed': '#23005c',
        'on-secondary-fixed-variant': '#5516be',
        'primary-fixed': '#e2dfff',
        'on-primary-fixed': '#0f0069',
        'on-tertiary-container': '#ffd4a4',
        'on-primary-fixed-variant': '#3323cc',
        'on-tertiary': '#ffffff',
        tertiary: '#684000',
        'outline-variant': '#c7c4d8',
        'secondary-fixed': '#e9ddff',
        'surface-container-high': '#e1e8fd',
        'on-secondary-container': '#fffbff',
        'surface-tint': '#4d44e3',
        success: '#10B981',
        'error-container': '#ffdad6',
        'on-tertiary-fixed': '#2a1700',
        'on-surface': '#141b2b',
        'border-base': '#E5E7EB',
        'primary-container': '#4f46e5',
        'on-surface-variant': '#464555',
        'tertiary-fixed-dim': '#ffb95f',
        'on-secondary': '#ffffff',
        'surface-bg': '#FFFFFF',
        'surface-bright': '#f9f9ff',
        'inverse-surface': '#293040',
        'ai-glow': 'rgba(139, 92, 246, 0.1)',
        background: '#f9f9ff',
        error: '#ba1a1a',
        'secondary-fixed-dim': '#d0bcff',
        outline: '#777587',
        'tertiary-container': '#885500',
        'tertiary-fixed': '#ffddb8',
        'inverse-on-surface': '#edf0ff',
        'surface-muted': '#F9FAFB',
        'surface-container-highest': '#dce2f7',
        'surface-dim': '#d3daef',
        'secondary-container': '#8455ef',
        'on-error': '#ffffff',
        'on-background': '#141b2b',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed-variant': '#653e00',
        'surface-container': '#e9edff',
        'surface-container-low': '#f1f3ff',
        'on-primary': '#ffffff',
        'surface-subtle': '#F3F4F6',
        secondary: '#6b38d4',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '8px',
        gutter: '24px',
        'stack-lg': '32px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        'container-max': '1280px',
        'stack-md': '16px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'headline-lg-mobile': ['Inter'],
        'label-md': ['JetBrains Mono'],
        'body-md': ['Inter'],
        'body-lg': ['Inter'],
        'headline-md': ['Inter'],
        'headline-lg': ['Inter'],
        'headline-xl': ['Inter'],
        'body-sm': ['Inter'],
        'label-sm': ['JetBrains Mono'],
      },
      fontSize: {
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}
