import { useRef, useState } from 'react'
import html2canvas from 'html2canvas'
import jsPDF from 'jspdf'
import { Button } from '@/components/ui/button'
import { Icon } from '@/components/shared/Icon'
import { SkillTag, DnaTag } from '@/components/shared/Tags'
import { SkillRadarChart } from '@/components/charts'
import { useAnalysis } from '@/hooks/useAnalysis'
import { useAuthStore } from '@/stores/authStore'
import { api } from '@/lib/api'
import { useTranslation } from '@/i18n/useTranslation'

export default function PortfolioPage() {
  const { analysis } = useAnalysis()
  const profile = useAuthStore((s) => s.profile)
  const previewRef = useRef<HTMLDivElement>(null)
  const [generating, setGenerating] = useState(false)
  const { t } = useTranslation()

  const handleExportPDF = async () => {
    if (!previewRef.current) return
    setGenerating(true)
    try {
      const canvas = await html2canvas(previewRef.current, { scale: 2 })
      const img = canvas.toDataURL('image/png')
      const pdf = new jsPDF('p', 'mm', 'a4')
      const w = pdf.internal.pageSize.getWidth()
      const h = (canvas.height * w) / canvas.width
      pdf.addImage(img, 'PNG', 0, 0, w, h)
      pdf.save(`${profile?.github_username || 'portfolio'}-devcompass.pdf`)
    } finally {
      setGenerating(false)
    }
  }

  const handleExportMarkdown = () => {
    if (!analysis) return
    const md = `# ${profile?.github_username || 'Developer'} — Portfolio

## ${analysis.developer_slogan}

${analysis.career_story}

## Developer DNA
${analysis.developer_dna.map((d) => `- ${d}`).join('\n')}

## Tech Stack
**Primary:** ${analysis.tech_stack.primary.join(', ')}
**Secondary:** ${analysis.tech_stack.secondary.join(', ')}
**Exploring:** ${analysis.tech_stack.exploring.join(', ')}

## Highlight Projects
${analysis.highlight_projects.map((p) => `### ${p.repo_name}\n${p.summary}\n*${p.key_contribution}*`).join('\n\n')}

---
*Generated by DevCompass*`
    const blob = new Blob([md], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${profile?.github_username || 'portfolio'}.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  const handleGenerate = async () => {
    setGenerating(true)
    try {
      await api.generatePortfolio()
    } finally {
      setGenerating(false)
    }
  }

  if (!analysis) {
    return (
      <div className="p-margin-desktop text-center py-20">
        <p className="text-on-surface-variant mb-4">{t('portfolio.empty')}</p>
        <Button onClick={handleGenerate} disabled={generating}>{t('portfolio.generateCta')}</Button>
      </div>
    )
  }

  return (
    <div className="p-margin-desktop max-w-container-max mx-auto space-y-stack-lg">
      <div className="flex justify-between items-start flex-wrap gap-4">
        <div>
          <h2 className="font-headline-lg text-headline-lg mb-2">{t('portfolio.title')}</h2>
          <p className="font-body-lg text-on-surface-variant">{t('portfolio.subtitle')}</p>
        </div>
        <div className="flex gap-3">
          <Button variant="secondary" onClick={handleExportMarkdown}>
            <Icon name="download" />
            {t('portfolio.markdown')}
          </Button>
          <Button onClick={handleExportPDF} disabled={generating}>
            <Icon name="picture_as_pdf" />
            {generating ? t('common.exporting') : t('portfolio.exportPdf')}
          </Button>
        </div>
      </div>

      <div ref={previewRef} className="bg-white border border-border-base rounded-2xl p-10 space-y-8">
        <header className="border-b border-border-base pb-8">
          <div className="flex items-center gap-6">
            {profile?.avatar_url && (
              <img src={profile.avatar_url} alt="" className="w-20 h-20 rounded-2xl" />
            )}
            <div>
              <h1 className="font-headline-lg text-headline-lg">{profile?.github_username}</h1>
              <p className="font-body-lg text-primary mt-1">{analysis.developer_slogan}</p>
            </div>
          </div>
        </header>

        <section>
          <h2 className="font-headline-md text-headline-md mb-4">{t('portfolio.about')}</h2>
          <p className="font-body-md text-on-surface-variant leading-relaxed">{analysis.career_story}</p>
        </section>

        <section>
          <h2 className="font-headline-md text-headline-md mb-4">{t('portfolio.developerDna')}</h2>
          <div className="flex flex-wrap gap-2">
            {analysis.developer_dna.map((d) => <DnaTag key={d}>{d}</DnaTag>)}
          </div>
        </section>

        <section className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div>
            <h2 className="font-headline-md text-headline-md mb-4">{t('portfolio.techStack')}</h2>
            <div className="space-y-3">
              <div><span className="font-label-md">{t('portfolio.primary')} </span>{analysis.tech_stack.primary.map((tech) => <SkillTag key={tech} className="ml-1 inline-block">{tech}</SkillTag>)}</div>
              <div><span className="font-label-md">{t('portfolio.secondary')} </span>{analysis.tech_stack.secondary.join(', ')}</div>
            </div>
          </div>
          <div>
            <h2 className="font-headline-md text-headline-md mb-4">{t('portfolio.skillRadar')}</h2>
            <SkillRadarChart scores={analysis.skill_scores} />
          </div>
        </section>

        <section>
          <h2 className="font-headline-md text-headline-md mb-4">{t('portfolio.projects')}</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {analysis.highlight_projects.map((p) => (
              <div key={p.repo_name} className="p-4 bg-surface-subtle rounded-xl border border-border-base">
                <h3 className="font-label-md font-bold">{p.repo_name}</h3>
                <p className="font-body-sm text-on-surface-variant mt-2">{p.summary}</p>
                <p className="font-body-sm text-primary mt-2">{p.key_contribution}</p>
              </div>
            ))}
          </div>
        </section>
      </div>
    </div>
  )
}
